INSERT INTO topic (name, description, meta, article_category_id) VALUES 
('Arquitetura e conceitos fundamentais', 'A importância da arquitetura e conceitos fundamentais', null, 1),
('Arquitetos e contratação', 'Análise e contratação de arquitetos', null, 1),
('Planejamento de obras', 'Planejamento de obras', null, 1),
('Projeto de arquitetura e custos', 'Projeto de arquitetura e custos', null, 1),
('Projetos de interiores', 'Projetos de interiores e decoração clean', null, 2),
('Banheiro, spa e ofurôs', 'Banheiro, spa e ofurôs', null, 2),
('Forros e sancas de gesso', 'Forros e sancas de gesso', null, 2),
('Ambientes comerciais', 'Decoração em ambientes comerciais', null, 2),
('Home office', 'Decoração em espaços home office', null, 2),
('Design de interiores', 'Design de interiores e decoração de ambientes', null, 2),
('Energia solar', 'Energia solar e sustentabilidade', null, 3),
('Sustentabilidade', 'Decoração sustentável', null, 3),
('Cisterna', 'Cisterna e sustentabilidade', null, 3),
('Jardins', 'Jardins e iluminação', null, 4),
('Lagos artificiais', 'Lagos artificiais', null, 4),
('Jardins de inverno', 'Jardins de inverno', null, 4);
